export const CHANGE_FIRSTNAME = 'CHANGE_FIRSTNAME';
export const CHANGE_SECONDNAME = 'CHANGE_SECONDNAME';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_CARDSBACK = 'CHANGE_CARDSBACK';
export const CHANGE_DIFFICULTY = 'CHANGE_DIFFICULTY';
export const INIT_CARDS = 'INIT_CARDS';
export const FLIP_CARD = 'FLIP_CARD';
export const CHECK_CARDS = 'CHECK_CARDS';
export const CHECK_IS_WIN = 'CHECK_IS_WIN';
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';
export const GET_RESULTS_FAILURE = 'GET_RESULTS_FAILURE';
export const UPDATE_SCORE = 'UPDATE_SCORE';

export const OPTIONS = {
  CHECK_CARDS_DELAY: 400,
  CHECK_WIN_DELAY: 1000,
  API_ENDPOINT: 'http://mmg-score.herokuapp.com'
}
